local testing

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,12 +20,19 @@ jobs:
 
     - name: Lint
       run: |
+        npm config set registry https://mavaddat.jfrog.io/artifactory/api/npm/default-npm-remote/
+        curl -u ${{ secrets.NPM_EMAIL}}:${{ secrets.JFROGPASS }} https://mavaddat.jfrog.io/artifactory/api/npm/auth >> ${{ github.workspace }}/.npmrc
         npm install --save-dev eslint && npm install eslint-config-google@latest && npm install --save-dev eslint-plugin-markdown
+        if [ $? -ne 0 ]; then
+          cat /home/runner/.npm/_logs/*.log
+          exit 1
+        fi
         echo 'module.exports = {\n\t"env": {\n\t\t"browser": true,\n\t\t"es2021": true\n\t},\n\t"extends": [\n\t\t"google"\n\t],\n\t"parserOptions": {\n\t\t"ecmaVersion": "latest",\n\t\t"sourceType": "module"\n\t},\n\t"rules": {\n\t}\n}\n' > .eslintrc.js
     - uses: reviewdog/action-eslint@v1
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
-        reporter: github-pr-review
+        reporter: github-check
+        workdir: ${{ github.workspace }}
         eslint_flags: .*.js source/*.js
 
   build:
@@ -44,7 +51,12 @@ jobs:
         npm config set registry https://mavaddat.jfrog.io/artifactory/api/npm/default-npm-remote/
         curl -u ${{ secrets.NPM_EMAIL}}:${{ secrets.JFROGPASS }} https://mavaddat.jfrog.io/artifactory/api/npm/auth >> ${{ github.workspace }}/.npmrc
         npm install async --dry-run --verbose
-        # if login failed, cat the newest log at /home/runner/.npm/_logs/*.log to see the error
+        # if login failed, dynamically get the npm log location from npm output
+        if [ $? -ne 0 ]; then
+          npm_log_location=$(grep 'npm WARN' ${{ github.workspace }}/.npm/_logs/*.log | awk '{print $6}')
+          echo "npm WARN: ${{ npm_log_location }}"
+          exit 1
+        fi
         if [ $? -ne 0 ]; then
           cat /home/runner/.npm/_logs/*.log
           exit 1
